// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class ClassGroup
{
    public int GroupId { get; set; }

    public string GroupName { get; set; }

    public string ProjectCode { get; set; }

    public string SemesterCode { get; set; }

    public int? LecturerId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    public virtual ICollection<JiraIssue> JiraIssues { get; set; } = new List<JiraIssue>();

    public virtual User Lecturer { get; set; }

    public virtual ProjectConfig ProjectConfig { get; set; }

    public virtual ICollection<ProjectReport> ProjectReports { get; set; } = new List<ProjectReport>();

    public virtual ICollection<ProjectReposNguyenLpk> ProjectReposNguyenLpks { get; set; } = new List<ProjectReposNguyenLpk>();

    public virtual Semester SemesterCodeNavigation { get; set; }

    public virtual ICollection<WorkLinksNguyenLpk> WorkLinksNguyenLpks { get; set; } = new List<WorkLinksNguyenLpk>();
}