// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class GithubIssuesNguyenLpk
{
    public long GhIssueId { get; set; }

    public int RepoId { get; set; }

    public int IssueNumber { get; set; }

    public string Title { get; set; }

    public string State { get; set; }

    public string AuthorGithubUsername { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ProjectReposNguyenLpk Repo { get; set; }
}