// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class GithubPrReviewsNguyenLpk
{
    public long ReviewId { get; set; }

    public long PrId { get; set; }

    public string ReviewerUsername { get; set; }

    public int? MappedReviewerId { get; set; }

    public string State { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public virtual GroupMember MappedReviewer { get; set; }

    public virtual GithubPullRequestsNguyenLpk Pr { get; set; }
}