// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class GithubCommitsNguyenLpk
{
    public long CommitId { get; set; }

    public string CommitHash { get; set; }

    public int RepoId { get; set; }

    public string Message { get; set; }

    public int? Additions { get; set; }

    public int? Deletions { get; set; }

    public DateTime? CommittedDate { get; set; }

    public string AuthorGithubUsername { get; set; }

    public int? MappedMemberId { get; set; }

    public string LinkedIssueKey { get; set; }

    public virtual GroupMember MappedMember { get; set; }

    public virtual ProjectReposNguyenLpk Repo { get; set; }
}