// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class GithubPullRequestsNguyenLpk
{
    public long PrId { get; set; }

    public int RepoId { get; set; }

    public int PrNumber { get; set; }

    public string Title { get; set; }

    public string State { get; set; }

    public bool? IsMerged { get; set; }

    public string AuthorGithubUsername { get; set; }

    public int? MappedMemberId { get; set; }

    public int? Additions { get; set; }

    public int? Deletions { get; set; }

    public int? ChangedFiles { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? MergedAt { get; set; }

    public DateTime? ClosedAt { get; set; }

    public string LinkedIssueKey { get; set; }

    public virtual ICollection<GithubPrReviewsNguyenLpk> GithubPrReviewsNguyenLpks { get; set; } = new List<GithubPrReviewsNguyenLpk>();

    public virtual GroupMember MappedMember { get; set; }

    public virtual ProjectReposNguyenLpk Repo { get; set; }
}