// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class GroupMember
{
    public int MemberId { get; set; }

    public int GroupId { get; set; }

    public int UserId { get; set; }

    public bool? IsLeader { get; set; }

    public string JiraAccountId { get; set; }

    public string GithubUsername { get; set; }

    public virtual ICollection<GithubCommitsNguyenLpk> GithubCommitsNguyenLpks { get; set; } = new List<GithubCommitsNguyenLpk>();

    public virtual ICollection<GithubPrReviewsNguyenLpk> GithubPrReviewsNguyenLpks { get; set; } = new List<GithubPrReviewsNguyenLpk>();

    public virtual ICollection<GithubPullRequestsNguyenLpk> GithubPullRequestsNguyenLpks { get; set; } = new List<GithubPullRequestsNguyenLpk>();

    public virtual ClassGroup Group { get; set; }

    public virtual ICollection<JiraIssue> JiraIssues { get; set; } = new List<JiraIssue>();

    public virtual User User { get; set; }
}