// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class JiraIssue
{
    public long IssueId { get; set; }

    public string IssueKey { get; set; }

    public int GroupId { get; set; }

    public string Summary { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public string IssueType { get; set; }

    public double? StoryPoints { get; set; }

    public string AssigneeAccountId { get; set; }

    public int? MappedMemberId { get; set; }

    public string ParentIssueKey { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ClassGroup Group { get; set; }

    public virtual GroupMember MappedMember { get; set; }
}