// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class ProjectConfig
{
    public int ConfigId { get; set; }

    public int? GroupId { get; set; }

    public string JiraUrl { get; set; }

    public string JiraEmail { get; set; }

    public string JiraApiToken { get; set; }

    public string JiraProjectKey { get; set; }

    public string GithubRepoUrl { get; set; }

    public string GithubToken { get; set; }

    public virtual ClassGroup Group { get; set; }
}