// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class ProjectReport
{
    public int ReportId { get; set; }

    public int GroupId { get; set; }

    public string ReportType { get; set; }

    public string FileUrl { get; set; }

    public string ReportData { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ClassGroup Group { get; set; }
}