// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class ProjectReposNguyenLpk
{
    public int RepoId { get; set; }

    public int GroupId { get; set; }

    public string RepoName { get; set; }

    public string RepoUrl { get; set; }

    public string RepoType { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<GithubCommitsNguyenLpk> GithubCommitsNguyenLpks { get; set; } = new List<GithubCommitsNguyenLpk>();

    public virtual ICollection<GithubIssuesNguyenLpk> GithubIssuesNguyenLpks { get; set; } = new List<GithubIssuesNguyenLpk>();

    public virtual ICollection<GithubPullRequestsNguyenLpk> GithubPullRequestsNguyenLpks { get; set; } = new List<GithubPullRequestsNguyenLpk>();

    public virtual ClassGroup Group { get; set; }
}