// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; }

    public string PasswordHash { get; set; }

    public string Role { get; set; }

    public string AvatarUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<ClassGroup> ClassGroups { get; set; } = new List<ClassGroup>();

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();
}