// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class WorkLinksNguyenLpk
{
    public long LinkId { get; set; }

    public int GroupId { get; set; }

    public string JiraIssueKey { get; set; }

    public string GithubEntityType { get; set; }

    public string GithubEntityId { get; set; }

    public DateTime? LinkedAt { get; set; }

    public virtual ClassGroup Group { get; set; }
}