// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace JirHub.Entities.NguyenLPK.Models;

public partial class prn222Context : DbContext
{
    public prn222Context()
    {
    }

    public prn222Context(DbContextOptions<prn222Context> options)
        : base(options)
    {
    }


    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);


    public virtual DbSet<ClassGroup> ClassGroups { get; set; }

    public virtual DbSet<GithubCommitsNguyenLpk> GithubCommitsNguyenLpks { get; set; }

    public virtual DbSet<GithubIssuesNguyenLpk> GithubIssuesNguyenLpks { get; set; }

    public virtual DbSet<GithubPrReviewsNguyenLpk> GithubPrReviewsNguyenLpks { get; set; }

    public virtual DbSet<GithubPullRequestsNguyenLpk> GithubPullRequestsNguyenLpks { get; set; }

    public virtual DbSet<GroupMember> GroupMembers { get; set; }

    public virtual DbSet<JiraIssue> JiraIssues { get; set; }

    public virtual DbSet<ProjectConfig> ProjectConfigs { get; set; }

    public virtual DbSet<ProjectReport> ProjectReports { get; set; }

    public virtual DbSet<ProjectReposNguyenLpk> ProjectReposNguyenLpks { get; set; }

    public virtual DbSet<Semester> Semesters { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<WorkLinksNguyenLpk> WorkLinksNguyenLpks { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ClassGroup>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK__class_gr__D57795A00EB0CF0E");

            entity.ToTable("class_groups");

            entity.HasIndex(e => e.ProjectCode, "UQ__class_gr__891B3A6FECE225CD").IsUnique();

            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.GroupName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("group_name");
            entity.Property(e => e.LecturerId).HasColumnName("lecturer_id");
            entity.Property(e => e.ProjectCode)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("project_code");
            entity.Property(e => e.SemesterCode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("semester_code");

            entity.HasOne(d => d.Lecturer).WithMany(p => p.ClassGroups)
                .HasForeignKey(d => d.LecturerId)
                .HasConstraintName("FK_class_groups_lecturer");

            entity.HasOne(d => d.SemesterCodeNavigation).WithMany(p => p.ClassGroups)
                .HasForeignKey(d => d.SemesterCode)
                .HasConstraintName("FK_class_groups_semester");
        });

        modelBuilder.Entity<GithubCommitsNguyenLpk>(entity =>
        {
            entity.HasKey(e => e.CommitId).HasName("PK__github_c__1C807873317C743C");

            entity.ToTable("github_commits_NguyenLPK");

            entity.HasIndex(e => e.AuthorGithubUsername, "IDX_commits_NguyenLPK_author");

            entity.HasIndex(e => e.RepoId, "IDX_commits_NguyenLPK_repo");

            entity.Property(e => e.CommitId).HasColumnName("commit_id");
            entity.Property(e => e.Additions).HasColumnName("additions");
            entity.Property(e => e.AuthorGithubUsername)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("author_github_username");
            entity.Property(e => e.CommitHash)
                .IsRequired()
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("commit_hash");
            entity.Property(e => e.CommittedDate).HasColumnName("committed_date");
            entity.Property(e => e.Deletions).HasColumnName("deletions");
            entity.Property(e => e.LinkedIssueKey)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("linked_issue_key");
            entity.Property(e => e.MappedMemberId).HasColumnName("mapped_member_id");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.RepoId).HasColumnName("repo_id");

            entity.HasOne(d => d.MappedMember).WithMany(p => p.GithubCommitsNguyenLpks)
                .HasForeignKey(d => d.MappedMemberId)
                .HasConstraintName("FK_commits_NguyenLPK_member");

            entity.HasOne(d => d.Repo).WithMany(p => p.GithubCommitsNguyenLpks)
                .HasForeignKey(d => d.RepoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_commits_NguyenLPK_repo");
        });

        modelBuilder.Entity<GithubIssuesNguyenLpk>(entity =>
        {
            entity.HasKey(e => e.GhIssueId).HasName("PK__github_i__D532755A5BD24B6A");

            entity.ToTable("github_issues_NguyenLPK");

            entity.Property(e => e.GhIssueId).HasColumnName("gh_issue_id");
            entity.Property(e => e.AuthorGithubUsername)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("author_github_username");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.IssueNumber).HasColumnName("issue_number");
            entity.Property(e => e.RepoId).HasColumnName("repo_id");
            entity.Property(e => e.State)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("state");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Repo).WithMany(p => p.GithubIssuesNguyenLpks)
                .HasForeignKey(d => d.RepoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_gh_issues_repo");
        });

        modelBuilder.Entity<GithubPrReviewsNguyenLpk>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__github_p__60883D906718C014");

            entity.ToTable("github_pr_reviews_NguyenLPK");

            entity.Property(e => e.ReviewId).HasColumnName("review_id");
            entity.Property(e => e.MappedReviewerId).HasColumnName("mapped_reviewer_id");
            entity.Property(e => e.PrId).HasColumnName("pr_id");
            entity.Property(e => e.ReviewerUsername)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("reviewer_username");
            entity.Property(e => e.State)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("state");
            entity.Property(e => e.SubmittedAt).HasColumnName("submitted_at");

            entity.HasOne(d => d.MappedReviewer).WithMany(p => p.GithubPrReviewsNguyenLpks)
                .HasForeignKey(d => d.MappedReviewerId)
                .HasConstraintName("FK_reviews_NguyenLPK_member");

            entity.HasOne(d => d.Pr).WithMany(p => p.GithubPrReviewsNguyenLpks)
                .HasForeignKey(d => d.PrId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_reviews_NguyenLPK_pr");
        });

        modelBuilder.Entity<GithubPullRequestsNguyenLpk>(entity =>
        {
            entity.HasKey(e => e.PrId).HasName("PK__github_p__47B09F8ED537FE7C");

            entity.ToTable("github_pull_requests_NguyenLPK");

            entity.HasIndex(e => e.RepoId, "IDX_pr_NguyenLPK_repo");

            entity.Property(e => e.PrId).HasColumnName("pr_id");
            entity.Property(e => e.Additions)
                .HasDefaultValue(0)
                .HasColumnName("additions");
            entity.Property(e => e.AuthorGithubUsername)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("author_github_username");
            entity.Property(e => e.ChangedFiles)
                .HasDefaultValue(0)
                .HasColumnName("changed_files");
            entity.Property(e => e.ClosedAt).HasColumnName("closed_at");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.Deletions)
                .HasDefaultValue(0)
                .HasColumnName("deletions");
            entity.Property(e => e.IsMerged)
                .HasDefaultValue(false)
                .HasColumnName("is_merged");
            entity.Property(e => e.LinkedIssueKey)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("linked_issue_key");
            entity.Property(e => e.MappedMemberId).HasColumnName("mapped_member_id");
            entity.Property(e => e.MergedAt).HasColumnName("merged_at");
            entity.Property(e => e.PrNumber).HasColumnName("pr_number");
            entity.Property(e => e.RepoId).HasColumnName("repo_id");
            entity.Property(e => e.State)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("state");
            entity.Property(e => e.Title).HasColumnName("title");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.MappedMember).WithMany(p => p.GithubPullRequestsNguyenLpks)
                .HasForeignKey(d => d.MappedMemberId)
                .HasConstraintName("FK_pr_NguyenLPK_member");

            entity.HasOne(d => d.Repo).WithMany(p => p.GithubPullRequestsNguyenLpks)
                .HasForeignKey(d => d.RepoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_pr_NguyenLPK_repo");
        });

        modelBuilder.Entity<GroupMember>(entity =>
        {
            entity.HasKey(e => e.MemberId).HasName("PK__group_me__B29B8534CE6F3B07");

            entity.ToTable("group_members");

            entity.HasIndex(e => new { e.GroupId, e.UserId }, "UQ_group_user").IsUnique();

            entity.Property(e => e.MemberId).HasColumnName("member_id");
            entity.Property(e => e.GithubUsername)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("github_username");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IsLeader)
                .HasDefaultValue(false)
                .HasColumnName("is_leader");
            entity.Property(e => e.JiraAccountId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("jira_account_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Group).WithMany(p => p.GroupMembers)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_group_members_group");

            entity.HasOne(d => d.User).WithMany(p => p.GroupMembers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_group_members_user");
        });

        modelBuilder.Entity<JiraIssue>(entity =>
        {
            entity.HasKey(e => e.IssueId).HasName("PK__jira_iss__D6185C3934209050");

            entity.ToTable("jira_issues");

            entity.HasIndex(e => e.GroupId, "IDX_jira_issues_group");

            entity.Property(e => e.IssueId).HasColumnName("issue_id");
            entity.Property(e => e.AssigneeAccountId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("assignee_account_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IssueKey)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("issue_key");
            entity.Property(e => e.IssueType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("issue_type");
            entity.Property(e => e.MappedMemberId).HasColumnName("mapped_member_id");
            entity.Property(e => e.ParentIssueKey)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("parent_issue_key");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.StoryPoints)
                .HasDefaultValue(0.0)
                .HasColumnName("story_points");
            entity.Property(e => e.Summary)
                .HasMaxLength(255)
                .HasColumnName("summary");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Group).WithMany(p => p.JiraIssues)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_jira_issues_group");

            entity.HasOne(d => d.MappedMember).WithMany(p => p.JiraIssues)
                .HasForeignKey(d => d.MappedMemberId)
                .HasConstraintName("FK_jira_issues_member");
        });

        modelBuilder.Entity<ProjectConfig>(entity =>
        {
            entity.HasKey(e => e.ConfigId).HasName("PK__project___4AD1BFF1701FB1DA");

            entity.ToTable("project_configs");

            entity.HasIndex(e => e.GroupId, "UQ__project___D57795A16B60A46E").IsUnique();

            entity.Property(e => e.ConfigId).HasColumnName("config_id");
            entity.Property(e => e.GithubRepoUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("github_repo_url");
            entity.Property(e => e.GithubToken).HasColumnName("github_token");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.JiraApiToken).HasColumnName("jira_api_token");
            entity.Property(e => e.JiraEmail)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("jira_email");
            entity.Property(e => e.JiraProjectKey)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("jira_project_key");
            entity.Property(e => e.JiraUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("jira_url");

            entity.HasOne(d => d.Group).WithOne(p => p.ProjectConfig)
                .HasForeignKey<ProjectConfig>(d => d.GroupId)
                .HasConstraintName("FK_project_configs_group");
        });

        modelBuilder.Entity<ProjectReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__project___779B7C58F4A407F5");

            entity.ToTable("project_reports");

            entity.Property(e => e.ReportId).HasColumnName("report_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.FileUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("file_url");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.ReportData).HasColumnName("report_data");
            entity.Property(e => e.ReportType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("report_type");

            entity.HasOne(d => d.Group).WithMany(p => p.ProjectReports)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_project_reports_group");
        });

        modelBuilder.Entity<ProjectReposNguyenLpk>(entity =>
        {
            entity.HasKey(e => e.RepoId).HasName("PK__project___E2D3BC805E15FD3E");

            entity.ToTable("project_repos_NguyenLPK");

            entity.Property(e => e.RepoId).HasColumnName("repo_id");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.RepoName)
                .HasMaxLength(255)
                .HasColumnName("repo_name");
            entity.Property(e => e.RepoType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("repo_type");
            entity.Property(e => e.RepoUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("repo_url");

            entity.HasOne(d => d.Group).WithMany(p => p.ProjectReposNguyenLpks)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_repos_NguyenLPK_group");
        });

        modelBuilder.Entity<Semester>(entity =>
        {
            entity.HasKey(e => e.SemesterCode).HasName("PK__semester__EC7D418B5A8F3511");

            entity.ToTable("semesters");

            entity.Property(e => e.SemesterCode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("semester_code");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__users__B9BE370F7C45A944");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "UQ__users__AB6E6164FF7E8B61").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("avatar_url");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("full_name");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password_hash");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("role");
        });

        modelBuilder.Entity<WorkLinksNguyenLpk>(entity =>
        {
            entity.HasKey(e => e.LinkId).HasName("PK__work_lin__93B0078CB16342EE");

            entity.ToTable("work_links_NguyenLPK");

            entity.HasIndex(e => e.GithubEntityId, "IDX_work_links_entity");

            entity.HasIndex(e => e.JiraIssueKey, "IDX_work_links_jira");

            entity.Property(e => e.LinkId).HasColumnName("link_id");
            entity.Property(e => e.GithubEntityId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("github_entity_id");
            entity.Property(e => e.GithubEntityType)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("github_entity_type");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.JiraIssueKey)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("jira_issue_key");
            entity.Property(e => e.LinkedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("linked_at");

            entity.HasOne(d => d.Group).WithMany(p => p.WorkLinksNguyenLpks)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_work_links_group");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}